### List all messages
GET http://localhost:3000/messages

###Create new messages
POST http://localhost:3000/messages
content-type: application/json

{
    "content": "OMG"
}

### Get particular message
GET http://localhost:3000/messages/6421